/// A single column definition under construction. Returned by the typed column
/// constructors (`t.uuid("id")`, `t.text("email")`, ...); modifiers chain and mutate the
/// definition in place:
///
/// ```swift
/// t.uuid("id").primaryKey().default(.raw("gen_random_uuid()"))
/// t.text("email").notNull().unique()
/// ```
public final class ColumnBuilder {
    let name: String
    let type: ColumnType

    private var isPrimaryKey = false
    private var isNotNull = false
    private var isUnique = false
    private var identity: Identity?
    private var defaultValue: DefaultValue?
    private var checkExpression: String?
    private var reference: Reference?

    private enum Identity {
        case always
        case byDefault
    }

    private struct Reference {
        let table: String
        let column: String
        let onDelete: ForeignKeyAction?
        let onUpdate: ForeignKeyAction?
    }

    init(name: String, type: ColumnType) {
        self.name = name
        self.type = type
    }

    /// Marks this column `PRIMARY KEY`. For a composite key use the table-level
    /// `t.primaryKey(["a", "b"])` instead.
    @discardableResult
    public func primaryKey() -> ColumnBuilder {
        isPrimaryKey = true
        return self
    }

    /// `NOT NULL`.
    @discardableResult
    public func notNull() -> ColumnBuilder {
        isNotNull = true
        return self
    }

    /// `UNIQUE`.
    @discardableResult
    public func unique() -> ColumnBuilder {
        isUnique = true
        return self
    }

    /// `DEFAULT <expression>`. Literals convert implicitly: `.default("member")`,
    /// `.default(0)`, `.default(true)`; expressions use `.default(.raw("gen_random_uuid()"))`.
    @discardableResult
    public func `default`(_ value: DefaultValue) -> ColumnBuilder {
        defaultValue = value
        return self
    }

    /// A column-level `CHECK (<expression>)` constraint. The expression is raw SQL.
    @discardableResult
    public func check(_ expression: String) -> ColumnBuilder {
        checkExpression = expression
        return self
    }

    /// A foreign key: `REFERENCES <table> (<column>)` with optional referential actions.
    @discardableResult
    public func references(
        _ table: String,
        _ column: String = "id",
        onDelete: ForeignKeyAction? = nil,
        onUpdate: ForeignKeyAction? = nil
    ) -> ColumnBuilder {
        reference = Reference(table: table, column: column, onDelete: onDelete, onUpdate: onUpdate)
        return self
    }

    /// `GENERATED ALWAYS AS IDENTITY` — the modern replacement for `SERIAL`.
    @discardableResult
    public func generatedAlwaysAsIdentity() -> ColumnBuilder {
        identity = .always
        return self
    }

    /// `GENERATED BY DEFAULT AS IDENTITY`.
    @discardableResult
    public func generatedByDefaultAsIdentity() -> ColumnBuilder {
        identity = .byDefault
        return self
    }

    /// Renders the column definition. Modifier order in the output is canonical and
    /// independent of chaining order.
    func render() -> String {
        var parts = [SQL.columnIdentifier(name), type.sql]
        switch identity {
        case .always: parts.append("GENERATED ALWAYS AS IDENTITY")
        case .byDefault: parts.append("GENERATED BY DEFAULT AS IDENTITY")
        case nil: break
        }
        if isPrimaryKey { parts.append("PRIMARY KEY") }
        if isNotNull { parts.append("NOT NULL") }
        if isUnique { parts.append("UNIQUE") }
        if let defaultValue { parts.append("DEFAULT \(defaultValue.sql)") }
        if let checkExpression { parts.append("CHECK (\(checkExpression))") }
        if let reference {
            var fk = "REFERENCES \(SQL.identifier(reference.table)) (\(SQL.columnIdentifier(reference.column)))"
            if let action = reference.onDelete { fk += " ON DELETE \(action.rawValue)" }
            if let action = reference.onUpdate { fk += " ON UPDATE \(action.rawValue)" }
            parts.append(fk)
        }
        return parts.joined(separator: " ")
    }
}

/// Anything that can define columns: shared by ``TableBuilder`` (columns of a new table)
/// and ``AlterTableBuilder`` (where each definition becomes an `ADD COLUMN`).
public protocol ColumnDefining: AnyObject {
    /// Defines a column with an explicit type. The typed conveniences below all funnel here.
    @discardableResult
    func column(_ name: String, _ type: ColumnType) -> ColumnBuilder
}

extension ColumnDefining {
    @discardableResult public func uuid(_ name: String) -> ColumnBuilder { column(name, .uuid) }
    @discardableResult public func text(_ name: String) -> ColumnBuilder { column(name, .text) }
    @discardableResult public func smallint(_ name: String) -> ColumnBuilder { column(name, .smallint) }
    @discardableResult public func integer(_ name: String) -> ColumnBuilder { column(name, .integer) }
    @discardableResult public func bigint(_ name: String) -> ColumnBuilder { column(name, .bigint) }
    @discardableResult public func boolean(_ name: String) -> ColumnBuilder { column(name, .boolean) }
    @discardableResult public func real(_ name: String) -> ColumnBuilder { column(name, .real) }
    @discardableResult public func doublePrecision(_ name: String) -> ColumnBuilder {
        column(name, .doublePrecision)
    }
    @discardableResult public func date(_ name: String) -> ColumnBuilder { column(name, .date) }
    @discardableResult public func time(_ name: String) -> ColumnBuilder { column(name, .time) }
    @discardableResult public func timestamp(_ name: String) -> ColumnBuilder { column(name, .timestamp) }
    @discardableResult public func timestamptz(_ name: String) -> ColumnBuilder {
        column(name, .timestamptz)
    }
    @discardableResult public func interval(_ name: String) -> ColumnBuilder { column(name, .interval) }
    @discardableResult public func json(_ name: String) -> ColumnBuilder { column(name, .json) }
    @discardableResult public func jsonb(_ name: String) -> ColumnBuilder { column(name, .jsonb) }
    @discardableResult public func bytea(_ name: String) -> ColumnBuilder { column(name, .bytea) }
    @discardableResult public func inet(_ name: String) -> ColumnBuilder { column(name, .inet) }

    @discardableResult
    public func varchar(_ name: String, limit: Int? = nil) -> ColumnBuilder {
        column(name, limit.map { .varchar($0) } ?? .varchar)
    }

    @discardableResult
    public func char(_ name: String, limit: Int? = nil) -> ColumnBuilder {
        column(name, limit.map { .char($0) } ?? .char)
    }

    @discardableResult
    public func numeric(_ name: String, precision: Int? = nil, scale: Int? = nil) -> ColumnBuilder {
        switch (precision, scale) {
        case (nil, _): return column(name, .numeric)
        case (let p?, nil): return column(name, .numeric(p))
        case (let p?, let s?): return column(name, .numeric(p, s))
        }
    }
}
