import Testing

@testable import FlightMigrate

@Suite("SchemaBuilder: createTable")
struct CreateTableTests {
    @Test func designDocumentExample() {
        let schema = SchemaBuilder()
        schema.createTable("users") { t in
            t.uuid("id").primaryKey().default(.raw("gen_random_uuid()"))
            t.text("email").notNull().unique()
            t.timestamptz("created_at").notNull().default(.now)
        }
        #expect(
            schema.statements == [
                """
                CREATE TABLE "users" (
                    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                    "email" TEXT NOT NULL UNIQUE,
                    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
                )
                """
            ])
    }

    @Test func modifierOrderIsCanonicalRegardlessOfChainOrder() {
        let a = SchemaBuilder()
        a.createTable("t") { t in t.text("c").default(.now).unique().notNull().primaryKey() }
        let b = SchemaBuilder()
        b.createTable("t") { t in t.text("c").primaryKey().notNull().unique().default(.now) }
        #expect(a.statements == b.statements)
    }

    @Test func ifNotExists() {
        let schema = SchemaBuilder()
        schema.createTable("t", ifNotExists: true) { t in t.integer("x") }
        #expect(schema.statements[0].hasPrefix("CREATE TABLE IF NOT EXISTS \"t\""))
    }

    @Test func columnTypes() {
        let schema = SchemaBuilder()
        schema.createTable("t") { t in
            t.smallint("a")
            t.bigint("b")
            t.boolean("c")
            t.real("d")
            t.doublePrecision("e")
            t.date("f")
            t.time("g")
            t.timestamp("h")
            t.interval("i")
            t.json("j")
            t.jsonb("k")
            t.bytea("l")
            t.inet("m")
            t.varchar("n", limit: 255)
            t.varchar("o")
            t.char("p", limit: 2)
            t.numeric("q", precision: 12, scale: 2)
            t.numeric("r", precision: 8)
            t.numeric("s")
            t.column("u", .array(of: .text))
            t.column("v", .custom("tsvector"))
        }
        let sql = schema.statements[0]
        #expect(sql.contains("\"a\" SMALLINT"))
        #expect(sql.contains("\"b\" BIGINT"))
        #expect(sql.contains("\"c\" BOOLEAN"))
        #expect(sql.contains("\"d\" REAL"))
        #expect(sql.contains("\"e\" DOUBLE PRECISION"))
        #expect(sql.contains("\"f\" DATE"))
        #expect(sql.contains("\"g\" TIME"))
        #expect(sql.contains("\"h\" TIMESTAMP,"))
        #expect(sql.contains("\"i\" INTERVAL"))
        #expect(sql.contains("\"j\" JSON,"))
        #expect(sql.contains("\"k\" JSONB"))
        #expect(sql.contains("\"l\" BYTEA"))
        #expect(sql.contains("\"m\" INET"))
        #expect(sql.contains("\"n\" VARCHAR(255)"))
        #expect(sql.contains("\"o\" VARCHAR,"))
        #expect(sql.contains("\"p\" CHAR(2)"))
        #expect(sql.contains("\"q\" NUMERIC(12, 2)"))
        #expect(sql.contains("\"r\" NUMERIC(8)"))
        #expect(sql.contains("\"s\" NUMERIC,"))
        #expect(sql.contains("\"u\" TEXT[]"))
        #expect(sql.contains("\"v\" tsvector"))
    }

    @Test func defaultValueRendering() {
        let schema = SchemaBuilder()
        schema.createTable("t") { t in
            t.text("a").default("it's")
            t.integer("b").default(42)
            t.doublePrecision("c").default(2.5)
            t.boolean("d").default(true)
            t.boolean("e").default(false)
            t.text("f").default(.null)
            t.jsonb("g").default(.raw("'{}'::jsonb"))
        }
        let sql = schema.statements[0]
        #expect(sql.contains("\"a\" TEXT DEFAULT 'it''s'"))
        #expect(sql.contains("\"b\" INTEGER DEFAULT 42"))
        #expect(sql.contains("\"c\" DOUBLE PRECISION DEFAULT 2.5"))
        #expect(sql.contains("\"d\" BOOLEAN DEFAULT TRUE"))
        #expect(sql.contains("\"e\" BOOLEAN DEFAULT FALSE"))
        #expect(sql.contains("\"f\" TEXT DEFAULT NULL"))
        #expect(sql.contains("\"g\" JSONB DEFAULT '{}'::jsonb"))
    }

    @Test func identityColumns() {
        let schema = SchemaBuilder()
        schema.createTable("t") { t in
            t.bigint("id").generatedAlwaysAsIdentity().primaryKey()
            t.bigint("alt").generatedByDefaultAsIdentity()
        }
        let sql = schema.statements[0]
        #expect(sql.contains("\"id\" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY"))
        #expect(sql.contains("\"alt\" BIGINT GENERATED BY DEFAULT AS IDENTITY"))
    }

    @Test func columnChecksAndReferences() {
        let schema = SchemaBuilder()
        schema.createTable("t") { t in
            t.integer("age").check("age >= 0")
            t.uuid("user_id").notNull()
                .references("users", onDelete: .cascade, onUpdate: .restrict)
            t.uuid("org_id").references("orgs", "org_key", onDelete: .setNull)
        }
        let sql = schema.statements[0]
        #expect(sql.contains("\"age\" INTEGER CHECK (age >= 0)"))
        #expect(
            sql.contains(
                "\"user_id\" UUID NOT NULL REFERENCES \"users\" (\"id\") ON DELETE CASCADE ON UPDATE RESTRICT"
            ))
        #expect(
            sql.contains("\"org_id\" UUID REFERENCES \"orgs\" (\"org_key\") ON DELETE SET NULL"))
    }

    @Test func tableConstraints() {
        let schema = SchemaBuilder()
        schema.createTable("t") { t in
            t.uuid("a")
            t.uuid("b")
            t.primaryKey(["a", "b"])
            t.unique(["a", "b"], name: "t_a_b_key")
            t.unique(["b"])
            t.check("a <> b", name: "distinct_ab")
            t.foreignKey(["a", "b"], references: "other", ["x", "y"], onDelete: .cascade)
        }
        let sql = schema.statements[0]
        #expect(sql.contains("    PRIMARY KEY (\"a\", \"b\")"))
        #expect(sql.contains("    CONSTRAINT \"t_a_b_key\" UNIQUE (\"a\", \"b\")"))
        #expect(sql.contains("    UNIQUE (\"b\")"))
        #expect(sql.contains("    CONSTRAINT \"distinct_ab\" CHECK (a <> b)"))
        #expect(
            sql.contains(
                "    FOREIGN KEY (\"a\", \"b\") REFERENCES \"other\" (\"x\", \"y\") ON DELETE CASCADE"
            ))
    }

    @Test func timestampsSugar() {
        let schema = SchemaBuilder()
        schema.createTable("t") { t in t.timestamps() }
        let sql = schema.statements[0]
        #expect(sql.contains("\"created_at\" TIMESTAMPTZ NOT NULL DEFAULT now()"))
        #expect(sql.contains("\"updated_at\" TIMESTAMPTZ NOT NULL DEFAULT now()"))
    }

    @Test func schemaQualifiedAndQuotedIdentifiers() {
        let schema = SchemaBuilder()
        schema.createTable("analytics.events") { t in
            t.text("weird\"name")
        }
        let sql = schema.statements[0]
        #expect(sql.hasPrefix("CREATE TABLE \"analytics\".\"events\""))
        #expect(sql.contains("\"weird\"\"name\" TEXT"))
    }
}

@Suite("SchemaBuilder: drop/rename/alter")
struct AlterTests {
    @Test func dropTableVariants() {
        let schema = SchemaBuilder()
        schema.dropTable("users")
        schema.dropTable("users", ifExists: true, cascade: true)
        #expect(schema.statements[0] == "DROP TABLE \"users\"")
        #expect(schema.statements[1] == "DROP TABLE IF EXISTS \"users\" CASCADE")
    }

    @Test func renameTable() {
        let schema = SchemaBuilder()
        schema.renameTable("old", to: "new")
        #expect(schema.statements == ["ALTER TABLE \"old\" RENAME TO \"new\""])
    }

    @Test func alterTableEmitsOneStatementPerActionInOrder() {
        let schema = SchemaBuilder()
        schema.alterTable("users") { t in
            t.text("bio").notNull().default("")
            t.addColumn("nick", .text, ifNotExists: true)
            t.dropColumn("legacy", ifExists: true, cascade: true)
            t.renameColumn("email", to: "email_address")
            t.setDefault("bio", .string("hi"))
            t.dropDefault("bio")
            t.setNotNull("bio")
            t.dropNotNull("bio")
            t.setDataType("count", .bigint, using: "count::bigint")
            t.addUnique(["email_address"], name: "users_email_key")
            t.addCheck("length(bio) < 500")
            t.addPrimaryKey(["id"])
            t.addForeignKey(["team_id"], references: "teams", onDelete: .cascade)
            t.dropConstraint("users_email_key", ifExists: true)
        }
        #expect(
            schema.statements == [
                "ALTER TABLE \"users\" ADD COLUMN \"bio\" TEXT NOT NULL DEFAULT ''",
                "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"nick\" TEXT",
                "ALTER TABLE \"users\" DROP COLUMN IF EXISTS \"legacy\" CASCADE",
                "ALTER TABLE \"users\" RENAME COLUMN \"email\" TO \"email_address\"",
                "ALTER TABLE \"users\" ALTER COLUMN \"bio\" SET DEFAULT 'hi'",
                "ALTER TABLE \"users\" ALTER COLUMN \"bio\" DROP DEFAULT",
                "ALTER TABLE \"users\" ALTER COLUMN \"bio\" SET NOT NULL",
                "ALTER TABLE \"users\" ALTER COLUMN \"bio\" DROP NOT NULL",
                "ALTER TABLE \"users\" ALTER COLUMN \"count\" TYPE BIGINT USING count::bigint",
                "ALTER TABLE \"users\" ADD CONSTRAINT \"users_email_key\" UNIQUE (\"email_address\")",
                "ALTER TABLE \"users\" ADD CHECK (length(bio) < 500)",
                "ALTER TABLE \"users\" ADD PRIMARY KEY (\"id\")",
                "ALTER TABLE \"users\" ADD FOREIGN KEY (\"team_id\") REFERENCES \"teams\" (\"id\") ON DELETE CASCADE",
                "ALTER TABLE \"users\" DROP CONSTRAINT IF EXISTS \"users_email_key\"",
            ])
    }

    @Test func lateModifiersOnAddedColumnAreCaptured() {
        // Modifiers applied after other actions still land on the right ADD COLUMN.
        let schema = SchemaBuilder()
        schema.alterTable("t") { t in
            let bio = t.text("bio")
            t.dropColumn("old")
            bio.notNull()
        }
        #expect(schema.statements[0] == "ALTER TABLE \"t\" ADD COLUMN \"bio\" TEXT NOT NULL")
        #expect(schema.statements[1] == "ALTER TABLE \"t\" DROP COLUMN \"old\"")
    }
}

@Suite("SchemaBuilder: indexes and extensions")
struct IndexTests {
    @Test func defaultNameUniquePartialAndMethod() {
        let schema = SchemaBuilder()
        schema.createIndex(on: "users", columns: ["email"])
        schema.createIndex(on: "users", columns: ["a", "b"], unique: true)
        schema.createIndex(
            on: "users", columns: ["email"], name: "custom_idx", ifNotExists: true,
            using: .gin, where: "deleted_at IS NULL")
        #expect(schema.statements[0] == "CREATE INDEX \"users_email_idx\" ON \"users\" (\"email\")")
        #expect(
            schema.statements[1]
                == "CREATE UNIQUE INDEX \"users_a_b_idx\" ON \"users\" (\"a\", \"b\")")
        #expect(
            schema.statements[2]
                == "CREATE INDEX IF NOT EXISTS \"custom_idx\" ON \"users\" USING GIN (\"email\") WHERE deleted_at IS NULL"
        )
    }

    @Test("a concurrent build defaults to IF NOT EXISTS so a retry can make progress")
    func concurrentIndexes() {
        let schema = SchemaBuilder()
        schema.createIndex(on: "users", columns: ["email"], concurrently: true)
        schema.dropIndex("users_email_idx", concurrently: true, ifExists: true)
        // A failed CONCURRENTLY build strands an INVALID index under this name,
        // and the migration was not in a transaction, so nothing rolled it back.
        // Without IF NOT EXISTS the retry dies on "relation already exists".
        #expect(
            schema.statements[0]
                == "CREATE INDEX CONCURRENTLY IF NOT EXISTS \"users_email_idx\" ON \"users\" (\"email\")")
        #expect(schema.statements[1] == "DROP INDEX CONCURRENTLY IF EXISTS \"users_email_idx\"")
    }

    @Test("the concurrent IF NOT EXISTS default can be declined explicitly")
    func concurrentIndexOptOut() {
        let schema = SchemaBuilder()
        schema.createIndex(on: "users", columns: ["email"], concurrently: true, ifNotExists: false)
        #expect(
            schema.statements[0]
                == "CREATE INDEX CONCURRENTLY \"users_email_idx\" ON \"users\" (\"email\")")
    }

    @Test("a non-concurrent build still defaults to plain CREATE INDEX")
    func nonConcurrentIndexUnchanged() {
        let schema = SchemaBuilder()
        schema.createIndex(on: "users", columns: ["email"])
        #expect(
            schema.statements[0]
                == "CREATE INDEX \"users_email_idx\" ON \"users\" (\"email\")")
    }

    @Test func indexNameStripsSchemaQualification() {
        let schema = SchemaBuilder()
        schema.createIndex(on: "audit.events", columns: ["at"])
        #expect(
            schema.statements[0]
                == "CREATE INDEX \"events_at_idx\" ON \"audit\".\"events\" (\"at\")")
    }

    @Test func extensions() {
        let schema = SchemaBuilder()
        schema.createExtension("pgcrypto")
        schema.createExtension("citext", ifNotExists: false)
        schema.dropExtension("citext", ifExists: true)
        #expect(schema.statements[0] == "CREATE EXTENSION IF NOT EXISTS \"pgcrypto\"")
        #expect(schema.statements[1] == "CREATE EXTENSION \"citext\"")
        #expect(schema.statements[2] == "DROP EXTENSION IF EXISTS \"citext\"")
    }
}

@Suite("SchemaBuilder: raw")
struct RawTests {
    @Test func rawIsVerbatimAndOrdered() {
        let schema = SchemaBuilder()
        schema.raw("UPDATE users SET a = 1")
        schema.dropTable("t")
        schema.raw("SELECT pg_notify('x', 'y')")
        #expect(
            schema.statements == [
                "UPDATE users SET a = 1",
                "DROP TABLE \"t\"",
                "SELECT pg_notify('x', 'y')",
            ])
    }

    @Test func trailingSemicolonsAndWhitespaceStripped() {
        let schema = SchemaBuilder()
        schema.raw("  DROP TABLE x;  ")
        schema.raw("DROP TABLE y;;\n")
        #expect(schema.statements == ["DROP TABLE x", "DROP TABLE y"])
    }

    @Test func internalSemicolonsPreserved() {
        let schema = SchemaBuilder()
        let function = """
            CREATE FUNCTION f() RETURNS void AS $$
            BEGIN
                UPDATE t SET a = 1;
            END;
            $$ LANGUAGE plpgsql
            """
        schema.raw(function)
        #expect(schema.statements == [function])
    }

    @Test func emptyStatementsIgnored() {
        let schema = SchemaBuilder()
        schema.raw("")
        schema.raw("   ;  ")
        #expect(schema.statements.isEmpty)
    }

    @Test("a default index name is truncated to Postgres' identifier limit")
    func longIndexNamesAreTruncatedDistinctly() {
        let table = String(repeating: "a", count: 50)
        let schema = SchemaBuilder()
        schema.createIndex(on: table, columns: [String(repeating: "b", count: 30)])
        schema.createIndex(on: table, columns: [String(repeating: "c", count: 30)])

        let names = schema.statements.map { statement -> String in
            // `CREATE INDEX "name" ON …`
            let afterIndex = statement.drop(while: { $0 != "\"" }).dropFirst()
            return String(afterIndex.prefix(while: { $0 != "\"" }))
        }
        for name in names {
            #expect(
                name.utf8.count <= 63,
                "Postgres truncates past 63 bytes silently; \(name.utf8.count) bytes does not fit")
        }
        // The hazard is not the length, it is two long names colliding after
        // the server truncates them — the second CREATE INDEX then fails, or an
        // IF NOT EXISTS one quietly does nothing.
        #expect(names[0] != names[1], "names sharing a long prefix must stay distinct")
    }

    @Test("DefaultValue.generatedUUID renders the builtin")
    func generatedUUIDDefault() {
        let schema = SchemaBuilder()
        schema.createTable("t") { t in
            t.uuid("id").primaryKey().default(.generatedUUID)
        }
        #expect(schema.statements[0].contains("DEFAULT gen_random_uuid()"))
    }
}
